DROP TABLE user_role IF EXISTS;
DROP TABLE user IF EXISTS;
DROP TABLE role IF EXISTS;

CREATE TABLE user (id BIGINT IDENTITY NOT NULL PRIMARY KEY, name VARCHAR(50), login VARCHAR(50), password VARCHAR(50));
CREATE TABLE role (id BIGINT IDENTITY NOT NULL PRIMARY KEY, name VARCHAR(50));
CREATE TABLE user_role (user_id BIGINT NOT NULL,role_id BIGINT  NOT NULL);
